services:
  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Postgres=Server=catalog-db;Port=5434;Database=Catalog;User Id=postgres;Password=postgres;Include Error Detail=true
    depends_on:
      - catalog-db
    ports:
      - "8080"
      - "8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  catalog-db:
    container_name: catalog-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=Catalog
    restart: always
    ports:
      - "5434:5432"
    volumes:
      - catalog-db:/var/lib/postgresql/data/
  auth-db:
    container_name: auth-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=Identity
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - auth-db:/var/lib/postgresql/data/