version: '3.4'

services:
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog.Api/Dockerfile
  catalog-db:
    image: postgres
  auth-db:
    image: postgres

volumes:
  catalog-db:  
  auth-db: